### ISSUE TITLE
pin_get returns paths to all cached pins including versioned one

### ISSUE THREAD

**Issue by cderv** [rstudio/pins#412] opened 2021-03-23 16:15 UTC
Working with a board on connect, I once retrieved an older version using `version = `

```r
> pins::pin_get("cderv/bookdownorg_books_meta", board = "rsconnect", version = 37847)
[1] "C:/Users/chris/AppData/Local/pins/pins/Cache/rsconnect/cderv/bookdownorg_books_meta/_versions/37847/_book_meta.rds"
```

But after, `pins::pin_get()` without `version = ` always returns paths to all cached pinned instead of just the named pin.
```r
> pins::pin_get("cderv/bookdownorg_books_meta", board = "rsconnect")
[1] "C:/Users/chris/AppData/Local/pins/pins/Cache/rsconnect/cderv/bookdownorg_books_meta/_book_meta.rds"                
[2] "C:/Users/chris/AppData/Local/pins/pins/Cache/rsconnect/cderv/bookdownorg_books_meta/_versions/37847/_book_meta.rds"
```

This is with CRAN version above.
Same with dev version and new `pin_read()` (which does provide support for version)

``` r
rsc_key <- Sys.getenv("RSC_BOOKDOWN_ORG_TOKEN", unset = "")
board <- board_rsconnect(server = "https://bookdown.org", key = rsc_key)
pin_read("cderv/bookdownorg_books_meta", board = board)
#> [1] "C:/Users/chris/AppData/Local/pins/pins/Cache/rsconnect/cderv/bookdownorg_books_meta/_book_meta.rds"                
#> [2] "C:/Users/chris/AppData/Local/pins/pins/Cache/rsconnect/cderv/bookdownorg_books_meta/_versions/36468/_book_meta.rds"
```

I would expect to only have the path of the named pin returned and not also its older versions as I did not specified version argument. More basically I would expect `pin_get` or `pîn_read` to result with only a single path.

I can build a reproducible example with a pin you can access if you need.

**Comment by hadley** [comment] 2021-04-15 20:17
This will get closed in the near future — I'm haven't actually checked that I've fixed you bug, but all the code now works with explicit lists of files rather than globs, so I'm pretty sure the problem is fixed.

**Closed** 2021-04-19 18:01 UTC
