### ISSUE TITLE
Getting Error : Some Vertex Names in edge list are not listed in  vertex data frame 

### ISSUE THREAD

**Issue by jayaraman94** [rstudio/pins#346] opened 2020-12-29 01:58 UTC
Hi,

I was trying to runApp by loading data as Pins. But, while doing that I am getting error while creating an igraph object with nodes and edges.

My Code Snippet
dat.net<- graph.data.frame(d = edges.df , directed = FALSE, vertices = nodes.df)

The error this throws;
Some Vertex Names in edge list are not listed in  vertex data frame

But while I perform the same by reading the data from my local, it works fine.

Looking on a fix for this.

Thanks,
Jay.

**Comment by javierluraschi** [comment] 2020-12-29 17:21
Duplicate of https://github.com/rstudio/pins/issues/347

**Closed by javierluraschi** 2020-12-29 17:21 UTC
